### ISSUE TITLE
Use the carousal to flip through applicable weather forecasts

### ISSUE THREAD

**Issue by Frankie-Figz** [Frankie-Figz/gwBootcampProject-1#9]
Potentially implement the following library to display the applicable weather forecasts

https://www.w3schools.com/bootstrap/bootstrap_carousel.asp

![image](https://user-images.githubusercontent.com/39884538/66274970-1b084580-e852-11e9-8fbf-347382cfee22.png)

The user could potentially cycle through the 12 weeks to see the distinct weather forecasts.

**Comment by aktran321** [comment]
I have this and will show you guys when we meet on Monday.

**Comment by Frankie-Figz** [comment]
This issue is not pertinent as it was decided to go against it
